<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAr8zEHQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAr8zEHQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAr8zEHQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAr8zEHQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAr8zEHQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ar8zEHQ',
    'container.build_id' => 'ff10e9c1',
    'container.build_time' => 1710165661,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAr8zEHQ');
